services:
  db:
    image: postgres:latest
    container_name: sweatmates_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: sweatmates_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    command: ["flask", "run", "--host=0.0.0.0"]

volumes:
  postgres_data:
